// ── Don't Look Down — pixel art roster ──────────────────────────────────────
// Sizes come from dldArtManifest.ts, generated by scripts/bake_dld_art.py. Every
// sprite is baked to the EXACT size it is drawn at, in buffer pixels, because
// the renderer blits each image 1:1 — one shared pixel grid with the character,
// sky and ground. Nothing is ever scaled at runtime.
//
// This module is pure data: no image imports, so the level generator (and its
// tests) can size platforms from real sprite dimensions without pulling PNGs
// into a test run. Loading the actual images is the renderer's job.
//
// Art plays one of three roles in the climb:
//   tile   — a square block meant to REPEAT. A platform is n tiles wide, which
//            is where the climb's variety of platform sizes comes from.
//   ledge  — a finished one-piece platform, used at its own natural width.
//   perch  — a themed object with a broad enough top to land on. Small, and
//            usually the thing a stage is asking you to hit exactly.

import { ART, type ArtId, type ArtTheme } from "./dldArtManifest";

export type { ArtId };
export type BlockId = ArtId;
export type BandId = Exclude<ArtTheme, "any">;
export type Role = "tile" | "ledge" | "perch";

/** Sprite size in WORLD units (the manifest is in buffer pixels). */
export const artW = (id: ArtId) => ART[id].w * 2;
export const artH = (id: ArtId) => ART[id].h * 2;

export const BAND_ORDER: BandId[] = ["school", "aqua", "farm", "desert", "city", "space"];

/**
 * Which blocks each band builds from. Blocks are theme-neutral art, so this is
 * what stops every band looking the same: the schoolyard is brick and
 * chalk-checker, the farm is timber and mud, orbit is metal and crystal. A few
 * are shared where they genuinely read both ways.
 */
const BAND_BLOCKS: Record<BandId, string[]> = {
  school: ["cube-grass", "cube-brick", "cube-checker", "cube-count", "cube-tally", "cube-crate",
           "plank-mossbrick", "plank-tile", "plank-grassledge", "plank-greybrick", "plank-palebrick",
           "slab-mossslab", "slab-paleslab"],
  aqua:   ["cube-pool", "cube-ice", "cube-slime", "cube-snow", "cube-stone",
           "plank-pebble", "plank-greystone", "plank-stonepair", "plank-greyledge",
           "slab-stoneslab"],
  farm:   ["cube-dirt", "cube-mud", "cube-grass", "cube-crate", "cube-mossy",
           "plank-wood", "plank-woodplank", "plank-darkwood", "plank-walnut", "plank-mossyledge",
           "plank-mossblock", "plank-mossledge", "plank-grassledge",
           "slab-plankslab", "slab-dirtslab", "slab-mossslab"],
  desert: ["cube-sand", "cube-clay", "cube-rust", "cube-cobble", "cube-stone",
           "plank-sandstone", "plank-sandledge", "plank-rubble", "plank-gravel",
           "plank-rockledge", "plank-brownbrick",
           "slab-dirtslab", "slab-paleslab"],
  city:   ["cube-concrete", "cube-metal", "cube-brick", "cube-candy", "cube-orchid",
           "plank-stonewall", "plank-panel", "plank-greybrick", "plank-greystone",
           "plank-greyledge", "plank-mossbrick2", "plank-palebrick", "plank-stonepair",
           "slab-stoneslab", "slab-paleslab"],
  space:  ["cube-amethyst", "cube-ember", "cube-lava", "cube-metal", "cube-ice",
           "cube-orchid", "cube-candy",
           "plank-panel", "plank-pebble", "plank-greystone", "plank-rockledge",
           "slab-stoneslab", "slab-plankslab"],
};

const isId = (s: string): s is ArtId => s in ART;

/** Everything a band can build a platform out of, by the role it plays. */
export const BAND_ART: Record<BandId, Record<Role, ArtId[]>> = Object.fromEntries(
  BAND_ORDER.map(band => {
    const pools: Record<Role, ArtId[]> = { tile: [], ledge: [], perch: [] };
    for (const n of BAND_BLOCKS[band]) {
      const id = `block-${n}`;
      if (isId(id)) pools[ART[id].family === "cube" ? "tile" : "ledge"].push(id);
    }
    for (const id of Object.keys(ART) as ArtId[]) {
      if (ART[id].kind === "prop" && ART[id].theme === band && ART[id].stand) pools.perch.push(id);
    }
    return [band, pools];
  }),
) as Record<BandId, Record<Role, ArtId[]>>;
