// GENERATED by scripts/bake_dld_scenery.py — do not edit by hand.
// w/h are BUFFER PIXELS: the exact size the renderer blits each piece at.
//
// Scenery is drawn and never collided with, so unlike a block it carries no
// family, theme or standability — just the size it was baked to.

export type SceneryEntry = { w: number; h: number };

export const SCENERY = {
  "scenery-apartment": { w: 93, h: 132 },
  "scenery-bench": { w: 42, h: 30 },
  "scenery-blackhole": { w: 350, h: 132 },
  "scenery-bush": { w: 40, h: 26 },
  "scenery-fence": { w: 35, h: 26 },
  "scenery-house": { w: 126, h: 74 },
  "scenery-lamp": { w: 30, h: 62 },
} as const satisfies Record<string, SceneryEntry>;

export type SceneryId = keyof typeof SCENERY;
