#!/usr/bin/env python3
"""Bake Don't Look Down SCENERY onto the game's pixel grid.

Scenery is the layer bake_dld_art.py has no room for. That script sizes every
prop to a 44px box, which is right for a bucket and useless for a four-storey
building or a black hole — those need their own budget, and they are never
landed on, so none of the standability rules apply to them either.

Deliberately separate from the block/prop manifest rather than folded into it:
the 201 baked blocks and props are what the climb's stages are built from, and
re-running a single script over a re-organised source folder would silently
change every platform in the game. This one only ever adds.

    python3 scripts/bake_dld_scenery.py "~/Downloads/claude assets down"
"""
import os, sys, glob
from PIL import Image

SRC = os.path.expanduser(sys.argv[1] if len(sys.argv) > 1 else "~/Downloads/claude assets down")
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "assets", "dld")
MANIFEST = os.path.join(os.path.dirname(__file__), "..", "src", "lib", "dldArtScenery.ts")

# name -> (source file, baked height in BUFFER PIXELS)
# For reference: a cube block bakes to 40px tall, the character is 28px.
PIECES = {
    "blackhole":  ("space/black-hole-portal.png", 132),
    "house":      ("city/house.png",               74),
    "apartment":  ("city/apartment-building.png", 132),
    "bench":      ("city/bench.png",               30),
    "bush":       ("city/bush.png",                26),
    "lamp":       ("city/street-lamp.png",         62),
    "fence":      ("farm/fence.png",               26),
}


def load(path):
    im = Image.open(path).convert("RGBA")
    bb = im.getbbox()
    return im.crop(bb) if bb else im


def main():
    for old in glob.glob(os.path.join(OUT, "scenery-*.png")):
        os.remove(old)

    entries = {}
    for name, (rel, target_h) in PIECES.items():
        path = os.path.join(SRC, rel)
        if not os.path.exists(path):
            raise SystemExit(f"missing source art: {path}")
        im = load(path)
        w = max(1, round(im.width * target_h / im.height))
        im2 = im.resize((w, target_h), Image.LANCZOS)
        key = f"scenery-{name}"
        im2.save(os.path.join(OUT, key + ".png"))
        entries[key] = (im2.width, im2.height)
        print(f"{key}: {im2.width}x{im2.height}")

    rows = "\n".join(f'  "{k}": {{ w: {w}, h: {h} }},' for k, (w, h) in sorted(entries.items()))
    with open(MANIFEST, "w") as fh:
        fh.write(
            "// GENERATED by scripts/bake_dld_scenery.py — do not edit by hand.\n"
            "// w/h are BUFFER PIXELS: the exact size the renderer blits each piece at.\n"
            "//\n"
            "// Scenery is drawn and never collided with, so unlike a block it carries no\n"
            "// family, theme or standability — just the size it was baked to.\n\n"
            "export type SceneryEntry = { w: number; h: number };\n\n"
            "export const SCENERY = {\n" + rows + "\n} as const satisfies Record<string, SceneryEntry>;\n\n"
            "export type SceneryId = keyof typeof SCENERY;\n")
    print(f"\nwrote {MANIFEST}")


if __name__ == "__main__":
    main()
